### ISSUE TITLE
Quark's mixed chest recipe takes priority over wisteria chests

### ISSUE THREAD

**Issue by fivelol** [c0d3break3r/Bloomful#13]
![image](https://user-images.githubusercontent.com/44749261/70340158-296de000-1848-11ea-8e2c-587d1a4133b2.png)
probably applies to bamboo chests

**Comment by fivelol** [comment]
relates to https://github.com/c0d3break3r/Bamboo-Blocks/issues/8 and vice versa

**Comment by bageldotjpg** [comment]
removed chests
