### ISSUE TITLE
Wandering trader doesnt sell wisteria saplings

### ISSUE THREAD

**Issue by WitheredWasabi** [c0d3break3r/Bloomful#21]

**Comment by fivelol** [comment]
it does though?

https://github.com/c0d3break3r/Bloomful/blob/4d0af3967ca54b1e09e72f42c80c4fc59fa32bfe/src/main/java/com/pugz/bloomful/core/util/EventHandler.java

**Comment by bageldotjpg** [comment]
Fixed
