### ISSUE TITLE
"Lower" leaves can spawn in place of main trunk

### ISSUE THREAD

**Issue by noobanidus** [c0d3break3r/Bloomful#25]
![](https://cdn.discordapp.com/attachments/460979039851511809/671429994727342100/unknown.png)

A check might need to be added when changing the blockstate to see if the blockstate is already a log (I'm rubbish with tree generators and last I checked everything was still obfuscated, otherwise I'd try to be more helpful with my issue, sorry!)

**Comment by fivelol** [comment]
this is a duplicate of #1 I believe

**Comment by noobanidus** [comment]
Ah, I didn't consider them "vines", sorry.
