### ISSUE TITLE
Mob spawns extremely low in the wisteria forest

### ISSUE THREAD

**Issue by fivelol** [c0d3break3r/Bloomful#3]
only seen a single rabbit within 5 minutes of exploring, other biomes have normal spawns

**Comment by SmellyModder** [comment]
The values for the rabbit spawns in the **WisteriaForestBiome** class are the same as the ones vanilla uses for the flower forest.

**Comment by SmellyModder** [comment]
Also to add to that; it looks like all the values for mob spawning are the same as vanilla's.
